package com.notification.enums;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    APPOINTMENT_BOOKED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED,
    PRESCRIPTION_VERIFIED,
    WELCOME
}
