server:
  port: 8082

spring:
  application:
    name: DOCTOR-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/doctor_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: Sandesh19
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: capsule-pharmacy-secret-key-very-long-and-secure-256-bit-key-here

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
